name: Update Languages

on:
  pull_request:
  workflow_dispatch:

jobs:
  update-languages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y jq curl

      - name: Fetch languages from Weblate API
        env:
          WEBLATE_API_TOKEN: ${{ secrets.WEBLATE_API_TOKEN }} # Add your API token as a GitHub secret
        run: |
          # Fetch the language list from the Weblate API
          curl -s -H "Authorization: Token ${WEBLATE_API_TOKEN}" https://translate.sysadminsmedia.com/api/languages/ > weblate_response.json
          cat weblate_response.json

      - name: Parse languages from Weblate API
        id: fetch_languages
        run: |
          # Extract 'name' and 'code' from Weblate API response and convert to JSON object
          LANGUAGES_JSON=$(jq -r '[.results[] | {(.code): .name}] | add' weblate_response.json)
          echo "LANGUAGES_JSON=${LANGUAGES_JSON}" >> $GITHUB_ENV

      - name: Check for changes in languages
        id: check_changes
        run: |
          # Extract the existing languages from the JSON file
          EXISTING_LANGUAGES=$(jq -c '.languages' frontend/locales/en.json)

          # Compare the new languages from Weblate with the existing ones
          if [ "${LANGUAGES_JSON}" = "${EXISTING_LANGUAGES}" ]; then
            echo "No new languages detected"
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "New languages detected"
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      - name: Update JSON file if necessary
        if: env.no_changes == 'false'
        run: |
          # Backup the original file
          cp frontend/locales/en.json frontend/locales/en.json.bak

          # Update the languages section in en.json
          jq --argjson newLanguages "${LANGUAGES_JSON}" '
            .languages = $newLanguages
          ' frontend/locales/en.json > frontend/locales/en.json.tmp

          # Move the temporary file back to en.json
          mv frontend/locales/en.json.tmp frontend/locales/en.json

      - name: Commit and push changes to new branch
        if: env.no_changes == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Delete existing branch if it exists
          git branch -D bot/update-languages || true
          git push origin --delete bot/update-languages || true

          # Create a new branch
          git checkout -b bot/update-languages

          # Commit changes
          git add frontend/locales/en.json
          git commit -m "Update languages in en.json"

          # Push the new branch
          git push --set-upstream origin bot/update-languages

      - name: Create pull request
        if: env.no_changes == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: bot/update-languages
          title: "Update languages in en.json"
          body: |
            This pull request updates the languages in `frontend/locales/en.json` based on the latest data from Weblate.
